spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@

swagger2:
  base-package: com.hc21cloud.generator
  title: hc21cloud代码生成模块
  version: 1.0.0
  description:
  contact:
    name: shaofeng
    url:
    email: 122107570@qq.com
# MyBatis
mybatis:
  # 自动扫描包路径给类配置别名
  typeAliasesPackage: com.hc21cloud.generator
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
